const SUPABASE_URL="https://mfdckngkvjnemwgmkiiv.supabase.co";
const PUBLIC_ANON="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mZGNrbmdrdmpuZW13Z21raWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYwMDcxMjUsImV4cCI6MjEwMTU4MzEyNX0.mFhv9hgQvjzg6AYfmEI2GiJ71I2xSkOozC43mwFcogU";
const RDC_LIST=['Jakarta','Semarang','Surabaya','Denpasar','Palembang'];
let SESSION=null,ACCESS=null,PERIOD='',SCOPE='',INCIDENTS=[],TYPE='delivery',CAUSE='Perjalanan',PHOTOS=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=v=>v==null?'—':Number(v).toLocaleString('id-ID',{maximumFractionDigits:2});
function logoSvg(size=64){return `<svg width="${size}" viewBox="0 0 100 80" aria-label="ROMAN"><path d="M12 47A38 38 0 0 1 88 47" fill="none" stroke="#ef1b2d" stroke-width="12"/><path d="M23 47A27 27 0 0 1 77 47" fill="none" stroke="#ffd21d" stroke-width="8"/><path d="M17 49h66l-8 10H25z" fill="#061b3c"/><circle cx="50" cy="48" r="8" fill="#ffd21d" stroke="#061b3c" stroke-width="4"/><text x="50" y="75" text-anchor="middle" font-size="18" font-weight="900" font-style="italic" fill="#ef1b2d">ROMAN</text></svg>`}
$('loginLogo').innerHTML=logoSvg();
function auth(){return SESSION?.access_token||PUBLIC_ANON}
function cleanErr(s){try{let j=JSON.parse(s);return j.message||j.error||s}catch{return s}}
async function rpc(fn,params={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${fn}`,{method:'POST',headers:{apikey:PUBLIC_ANON,Authorization:`Bearer ${auth()}`,'Content-Type':'application/json'},body:JSON.stringify(params)});if(!r.ok)throw new Error(await r.text());return r.json()}
async function signIn(username,pw){username=String(username||'').trim().toLowerCase();if(!username||!pw)throw new Error('User ID dan password wajib.');const email=await rpc('get_login_email',{input_username:username,input_password:pw});if(!email)throw new Error('User ID atau password salah.');const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:PUBLIC_ANON,'Content-Type':'application/json'},body:JSON.stringify({email,password:pw})});if(!r.ok)throw new Error('Login gagal. Periksa User ID dan password.');SESSION=await r.json();ACCESS=await rpc('breakage_my_access_v44',{});sessionStorage.setItem('sls_breakage_input_session',JSON.stringify(SESSION));sessionStorage.setItem('sls_breakage_input_username',username)}
function currentPeriod(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function monthName(p){const [y,m]=p.split('-').map(Number);return new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(new Date(y,m-1,1))}
function initPeriods(){PERIOD=PERIOD||currentPeriod();let d=new Date(),a=[];for(let i=-6;i<=1;i++){let x=new Date(d.getFullYear(),d.getMonth()+i,1);a.push(`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`)}$('period').innerHTML=a.map(p=>`<option value="${p}" ${p===PERIOD?'selected':''}>${monthName(p)}</option>`).join('');$('periodLabel').textContent=monthName(PERIOD)}
function effectiveScope(){return ACCESS?.is_master?SCOPE:ACCESS?.rdc_name}
function showApp(){$('login').style.display='none';$('app').style.display='block';$('who').textContent=`${String(ACCESS.role||'').toUpperCase()} · ${ACCESS.is_master?'Master / Nasional':ACCESS.rdc_name}`;$('rdcCard').textContent=ACCESS.is_master?(SCOPE||'Pilih RDC'):ACCESS.rdc_name;if(ACCESS.is_master)$('masterScope').classList.add('show');else $('masterScope').classList.remove('show');if(!ACCESS.can_input){$('newBtn').classList.add('hidden');$('navInput').classList.add('hidden');$('roleMsg').classList.remove('hidden');$('roleMsg').innerHTML='<b>Akun ini tidak memiliki hak input incident.</b> Gunakan akun Supervisor/SPV untuk entry. Akun ini tetap dapat melihat riwayat sesuai scope.'}else{$('newBtn').classList.remove('hidden');$('navInput').classList.remove('hidden');$('roleMsg').classList.add('hidden')}}
async function loadHistory(){try{let s=effectiveScope();if(ACCESS.is_master&&!s){INCIDENTS=[];renderHistory();return}INCIDENTS=await rpc('breakage_incident_list',{p_period:PERIOD,p_rdc:s})||[];renderHistory()}catch(e){$('historyBody').innerHTML=`<tr><td colspan="8"><div class="empty">Gagal memuat: ${esc(cleanErr(e.message))}</div></td></tr>`}}
function renderHistory(){$('countCard').textContent=fmt(INCIDENTS.length);$('qtyCard').textContent=fmt(INCIDENTS.reduce((a,b)=>a+Number(b.qty_box||0),0));$('rdcCard').textContent=ACCESS.is_master?(SCOPE||'Pilih RDC'):ACCESS.rdc_name;$('historyBody').innerHTML=INCIDENTS.length?INCIDENTS.slice(0,50).map(r=>`<tr><td>${esc(r.incident_no)}</td><td>${esc(r.occurrence_date)}</td><td>${esc(r.incident_type)}</td><td>${esc(r.item_code)}</td><td>${fmt(r.qty_box)} ${esc(r.uom||'BOX')}</td><td>${esc(r.no_ba)}</td><td>${esc(r.reported_by)}</td><td><span class="badge ${String(r.status).toUpperCase()==='CLOSED'?'good':'watch'}">${esc(r.status)}</span></td></tr>`).join(''):`<tr><td colspan="8"><div class="empty">Belum ada incident untuk ${esc(monthName(PERIOD))}.</div></td></tr>`}
async function login(){let u=$('username').value.trim(),pw=$('pw').value;$('loginMsg').textContent='';try{await signIn(u,pw);PERIOD=currentPeriod();SCOPE=ACCESS.is_master?'Jakarta':ACCESS.rdc_name;initPeriods();showApp();await loadHistory()}catch(e){$('loginMsg').textContent=cleanErr(e.message)}}
async function restoreSession(){let raw=sessionStorage.getItem('sls_breakage_input_session');$('username').value=sessionStorage.getItem('sls_breakage_input_username')||'';if(!raw)return;try{SESSION=JSON.parse(raw);ACCESS=await rpc('breakage_my_access_v44',{});PERIOD=currentPeriod();SCOPE=ACCESS.is_master?'Jakarta':ACCESS.rdc_name;initPeriods();showApp();await loadHistory()}catch(e){sessionStorage.removeItem('sls_breakage_input_session')}}
async function logout(){try{if(SESSION?.access_token)await fetch(`${SUPABASE_URL}/auth/v1/logout`,{method:'POST',headers:{apikey:PUBLIC_ANON,Authorization:`Bearer ${SESSION.access_token}`}})}catch(_e){}sessionStorage.removeItem('sls_breakage_input_session');sessionStorage.removeItem('sls_breakage_input_username');location.reload()}
$('loginBtn').onclick=login;['username','pw'].forEach(id=>$(id).onkeydown=e=>{if(e.key==='Enter')login()});$('logoutBtn').onclick=logout;$('navLogout').onclick=logout;$('refreshBtn').onclick=loadHistory;$('navHome').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});$('navHistory').onclick=()=>document.querySelector('.panel').scrollIntoView({behavior:'smooth'});$('newBtn').onclick=()=>openInput();$('navInput').onclick=()=>openInput();
$('period').onchange=async e=>{PERIOD=e.target.value;$('periodLabel').textContent=monthName(PERIOD);await loadHistory()};$('scope').onchange=async e=>{SCOPE=e.target.value;await loadHistory()};
function draftKey(){return 'sls_breakage_input_draft_'+(ACCESS?.username||sessionStorage.getItem('sls_breakage_input_username')||'user')}
function openInput(){if(!ACCESS?.can_input){alert('Akun ini tidak memiliki hak input incident.');return}let rdc=effectiveScope();if(!rdc){alert('Pilih RDC terlebih dahulu.');return}$('incidentModal').classList.add('show');$('fRdc').value=rdc;$('fInputBy').value=ACCESS.username||ACCESS.role;$('inputIdentity').textContent=`${String(ACCESS.role).toUpperCase()} · ${rdc}`;$('fDate').value=new Date().toISOString().slice(0,10);restoreDraft();renderPhotos()}
$('closeModal').onclick=()=>$('incidentModal').classList.remove('show');
function renderConditional(t){TYPE=t;document.querySelectorAll('#typeTabs button').forEach(b=>b.classList.toggle('active',b.dataset.type===t));let el=$('conditional');if(t==='delivery')el.innerHTML=`<div class="form-grid"><div class="field"><label>No SJ *</label><input id="fSj"></div><div class="field"><label>Customer *</label><input id="fCustomer"></div><div class="field"><label>Transporter *</label><input id="fTransporter"></div><div class="field"><label>Driver *</label><input id="fDriver"></div><div class="field span2"><label>No Polisi *</label><input id="fPolice"></div></div>`;else if(t==='receiving')el.innerHTML=`<div class="form-grid"><div class="field"><label>No SJ *</label><input id="fSj"></div><div class="field"><label>Factory *</label><select id="fFactory"><option value="">Pilih</option><option>SRKI</option><option>RCI</option></select></div><div class="field"><label>Transporter *</label><input id="fTransporter"></div><div class="field"><label>Driver *</label><input id="fDriver"></div><div class="field span2"><label>No Polisi *</label><input id="fPolice"></div></div>`;else el.innerHTML=`<div class="form-grid"><div class="field"><label>Kejadian Gudang *</label><select id="fWhEvent"><option value="Pecah Dalam Pallet">Pecah Dalam Pallet</option><option value="Misshandling">Misshandling</option></select></div><div class="field"><label>Nama terkait (wajib jika Misshandling)</label><input id="fRelated"></div></div>`;bindDraftInputs()}
document.querySelectorAll('#typeTabs button').forEach(b=>b.onclick=()=>renderConditional(b.dataset.type));document.querySelectorAll('#causeTabs button').forEach(b=>b.onclick=()=>{CAUSE=b.dataset.cause;document.querySelectorAll('#causeTabs button').forEach(x=>x.classList.toggle('active',x===b));saveDraft()});
function formData(){return {type:TYPE,cause:CAUSE,date:$('fDate').value,ba:$('fBa').value,item:$('fItem').value,qty:$('fQty').value,reported:$('fReported').value,sj:$('fSj')?.value||'',factory:$('fFactory')?.value||'',customer:$('fCustomer')?.value||'',transporter:$('fTransporter')?.value||'',driver:$('fDriver')?.value||'',police:$('fPolice')?.value||'',wh:$('fWhEvent')?.value||'',related:$('fRelated')?.value||'',detail:$('fCauseDetail').value}}
function saveDraft(){localStorage.setItem(draftKey(),JSON.stringify(formData()));$('draftStatus').textContent='Draft otomatis tersimpan'}
function restoreDraft(){try{let d=JSON.parse(localStorage.getItem(draftKey())||'{}');TYPE=d.type||'delivery';CAUSE=d.cause||'Perjalanan';renderConditional(TYPE);[['fDate','date'],['fBa','ba'],['fItem','item'],['fQty','qty'],['fReported','reported'],['fCauseDetail','detail']].forEach(([id,k])=>{if(d[k])$(id).value=d[k]});setTimeout(()=>{[['fSj','sj'],['fFactory','factory'],['fCustomer','customer'],['fTransporter','transporter'],['fDriver','driver'],['fPolice','police'],['fWhEvent','wh'],['fRelated','related']].forEach(([id,k])=>{if($(id)&&d[k])$(id).value=d[k]})},0);document.querySelectorAll('#causeTabs button').forEach(b=>b.classList.toggle('active',b.dataset.cause===CAUSE))}catch(_e){}}
function bindDraftInputs(){document.querySelectorAll('#incidentModal input,#incidentModal select,#incidentModal textarea').forEach(x=>{if(x.id!=='fPhotos')x.oninput=saveDraft})}bindDraftInputs();$('saveDraft').onclick=()=>{saveDraft();$('draftStatus').textContent='Draft disimpan'};
$('fPhotos').onchange=e=>{let arr=Array.from(e.target.files||[]);if(arr.length>5){alert('Maksimal 5 foto.');e.target.value='';return}PHOTOS=arr;renderPhotos()};function renderPhotos(){$('photoPreview').innerHTML=[0,1,2,3,4].map(i=>`<div class="ph">${PHOTOS[i]?`<img src="${URL.createObjectURL(PHOTOS[i])}"><b>${i+1}</b>`:`<b>${i+1}</b>`}</div>`).join('')}
function validateIncident(){let d=formData(),m=[];if(!d.date)m.push('Tanggal');if(!d.ba)m.push('No BA');if(!d.item)m.push('Kode Item');if(!(Number(d.qty)>0))m.push('Qty');if(!d.reported)m.push('Reported By');if(PHOTOS.length<1)m.push('Foto');if(TYPE==='delivery'){if(!d.sj)m.push('No SJ');if(!d.customer)m.push('Customer');if(!d.transporter)m.push('Transporter');if(!d.driver)m.push('Driver');if(!d.police)m.push('No Polisi')}if(TYPE==='receiving'){if(!d.sj)m.push('No SJ');if(!d.factory)m.push('Factory');if(!d.transporter)m.push('Transporter');if(!d.driver)m.push('Driver');if(!d.police)m.push('No Polisi')}if(TYPE==='warehouse'&&d.wh==='Misshandling'&&!d.related)m.push('Nama terkait');if(CAUSE==='Lainnya'&&!d.detail)m.push('Keterangan penyebab');return m}
async function uploadEvidence(files,rdc){let batch='draft_'+crypto.randomUUID(),paths=[];for(let i=0;i<files.length;i++){let f=files[i],ext=(f.name.split('.').pop()||'jpg').toLowerCase(),safe=String(rdc).replace(/[^A-Za-z0-9_-]/g,'_'),path=`${safe}/${batch}/${Date.now()}_${i+1}.${ext}`;let r=await fetch(`${SUPABASE_URL}/storage/v1/object/breakage-evidence/${encodeURI(path)}`,{method:'POST',headers:{apikey:PUBLIC_ANON,Authorization:`Bearer ${auth()}`,'Content-Type':f.type||'image/jpeg','x-upsert':'false'},body:f});if(!r.ok)throw new Error('Upload foto gagal: '+await r.text());paths.push(path)}return paths}
function resetForm(){['fBa','fItem','fQty','fReported','fCauseDetail'].forEach(id=>$(id).value='');PHOTOS=[];TYPE='delivery';CAUSE='Perjalanan';renderConditional(TYPE);renderPhotos();document.querySelectorAll('#causeTabs button').forEach(b=>b.classList.toggle('active',b.dataset.cause===CAUSE));$('fDate').value=new Date().toISOString().slice(0,10)}
$('submitIncident').onclick=async()=>{let miss=validateIncident(),msg=$('inputMsg');msg.classList.remove('hidden');if(miss.length){msg.style.color='#c42d26';msg.textContent='Mohon lengkapi: '+miss.join(', ');return}let b=$('submitIncident');b.disabled=true;msg.style.color='#6f7b91';msg.textContent='Menyimpan evidence dan incident…';try{let d=formData(),rdc=effectiveScope(),paths=await uploadEvidence(PHOTOS,rdc);let payload={incident_type:TYPE,occurrence_date:d.date,item_code:d.item,qty_box:Number(d.qty),uom:'BOX',rdc_name:rdc,no_ba:d.ba.toUpperCase(),reported_by:d.reported,no_sj:d.sj,factory:d.factory,customer:d.customer,transporter:d.transporter,driver_name:d.driver,vehicle_no:d.police.toUpperCase(),cause:CAUSE,cause_detail:d.detail,warehouse_event:d.wh,related_person:d.related,photo_paths:paths};let res=await rpc('breakage_incident_create_v44',{p_payload:payload});msg.style.color='#079455';msg.textContent=`Tersimpan ${res.incident_no} · BA ${res.no_ba}`;localStorage.removeItem(draftKey());resetForm();setTimeout(async()=>{$('incidentModal').classList.remove('show');PERIOD=d.date.slice(0,7);initPeriods();await loadHistory();document.querySelector('.panel').scrollIntoView({behavior:'smooth'})},750)}catch(e){msg.style.color='#c42d26';msg.textContent='Gagal: '+cleanErr(e.message)}finally{b.disabled=false}};
restoreSession();
