// SLS Breakage Input v53 — SPV evidence completeness guard + auto BA submit hotfix.
// Evidence rule: minimum 1 and maximum 5 photos per incident, independent of broken BOX quantity.
(function(){
  const BUILD_LABEL='BUILD v53';

  function setBuild(){
    const el=document.getElementById('slsBuildBadge');
    if(el) el.textContent=BUILD_LABEL;
  }
  setBuild();

  // runtime_patch v50 still owns compression/session logic. Re-assert current build after
  // every render/history load so the displayed build reflects the active hotfix.
  if(typeof loadHistory==='function'){
    const baseLoadHistoryV53=loadHistory;
    loadHistory=async function(){
      try{return await baseLoadHistoryV53.apply(this,arguments)}
      finally{setBuild()}
    };
    window.loadHistory=loadHistory;
  }
  if(typeof showApp==='function'){
    const baseShowAppV53=showApp;
    showApp=function(){
      const out=baseShowAppV53.apply(this,arguments);
      setBuild();
      return out;
    };
    window.showApp=showApp;
  }

  function incidentById(id){return (INCIDENTS||[]).find(x=>Number(x.incident_id)===Number(id))}
  function requiredEvidence(_r){return 1}
  function evidenceCount(r){return Array.isArray(r?.photo_paths)?r.photo_paths.filter(Boolean).length:0}
  function evidenceComplete(r){const n=evidenceCount(r);return n>=1&&n<=5}
  const up=v=>String(v??'').trim().toUpperCase();

  function renderEvidenceRule(r){
    const details=$('reviewDetails');if(!details)return;
    let box=document.getElementById('reviewEvidenceRule');
    if(!box){
      box=document.createElement('div');box.id='reviewEvidenceRule';box.className='hint';box.style.cssText='grid-column:1/-1;margin-bottom:2px;font-weight:700';
      details.parentNode.insertBefore(box,details.nextSibling);
    }
    const got=evidenceCount(r),ok=evidenceComplete(r);
    box.style.borderColor=ok?'#b7e2ca':'#ffc9c6';
    box.style.background=ok?'#e8f7ef':'#fff0ef';
    box.style.color=ok?'#067647':'#c42d26';
    box.innerHTML=ok
      ? `✓ Evidence lengkap: <b>${got} foto</b> untuk incident ${Number(r.qty_box||0)} BOX. Rule: 1–5 foto per incident.`
      : `⚠ Evidence belum lengkap. Minimal <b>1 foto</b> dan maksimal <b>5 foto</b> per incident. SPV hanya dapat <b>Return ke Admin</b> sampai evidence dilengkapi.`;
  }

  if(typeof viewIncident==='function'){
    const baseViewIncident=viewIncident;
    viewIncident=async function(id){
      await baseViewIncident(id);
      setBuild();
      const r=incidentById(id);if(!r)return;
      renderEvidenceRule(r);
      if(!evidenceComplete(r)){
        REVIEW_PHOTOS_READY=false;
        $('reviewChecked').checked=false;
        $('reviewChecked').disabled=true;
        const label=$('reviewChecked')?.closest('label');if(label)label.style.opacity='.55';
        $('reviewMsg').textContent=`Evidence ${evidenceCount(r)} foto. Rule wajib 1–5 foto per incident. Kembalikan ke Admin untuk melengkapi evidence.`;
      }else{
        $('reviewChecked').disabled=false;
        const label=$('reviewChecked')?.closest('label');if(label)label.style.opacity='1';
      }
      syncReviewButtons();
    };
    window.viewIncident=viewIncident;
  }

  if(typeof submitSpvReview==='function'){
    const baseSubmitSpvReview=submitSpvReview;
    submitSpvReview=async function(decision){
      const r=incidentById(REVIEW_ID);
      if(decision==='APPROVE'&&r&&!evidenceComplete(r)){
        $('reviewMsg').textContent=`Approval ditahan: evidence ${evidenceCount(r)} foto. Minimal 1 dan maksimal 5 foto per incident.`;
        setBuild();
        return;
      }
      try{return await baseSubmitSpvReview(decision)}
      finally{setBuild()}
    };
    window.submitSpvReview=submitSpvReview;
    $('returnReview').onclick=()=>submitSpvReview('RETURN');
    $('approveReview').onclick=()=>submitSpvReview('APPROVE');
  }

  // No BA is generated by Supabase backend. The old runtime v50
  // still referenced d.ba.toUpperCase(), while formData no longer has d.ba.
  // Replace the submit handler after runtime_patch has loaded.
  if($('submitIncident')){
    $('submitIncident').onclick=async()=>{
      const miss=validateIncident(),msg=$('inputMsg');
      msg.classList.remove('hidden');
      if(miss.length){msg.style.color='#c42d26';msg.textContent='Mohon lengkapi: '+miss.join(', ');return}
      const b=$('submitIncident');
      b.disabled=true;
      msg.style.color='#6f7b91';
      msg.textContent=EDIT_ID?'Mengompresi foto & memperbarui Draft…':'Mengompresi foto & menyimpan Draft ke sistem…';
      try{
        const d=formData(),rdc=effectiveScope(),newPaths=PHOTOS.length?await uploadEvidence(PHOTOS,rdc):[],paths=[...(EXISTING_PHOTO_PATHS||[]),...newPaths];
        if(paths.length<1)throw new Error('Foto dokumentasi wajib.');
        if(paths.length>5)throw new Error('Maksimal 5 foto per incident.');
        const payload={
          incident_type:TYPE,
          occurrence_date:d.date,
          item_code:up(d.item),
          qty_box:Number(d.qty),
          uom:'BOX',
          rdc_name:rdc,
          reported_by:up(d.reported),
          no_sj:up(d.sj),
          factory:up(d.factory),
          customer:up(d.customer),
          transporter:up(d.transporter),
          driver_name:up(d.driver),
          vehicle_no:up(d.police),
          cause:CAUSE,
          cause_detail:up(d.detail),
          warehouse_event:d.wh,
          related_person:up(d.related),
          photo_paths:paths
        };
        // no_ba intentionally omitted: generated atomically by breakage_incident_create_v45.
        const res=EDIT_ID
          ? await rpc('breakage_incident_update_draft_v45',{p_incident_id:EDIT_ID,p_payload:payload})
          : await rpc('breakage_incident_create_v45',{p_payload:payload});
        msg.style.color='#079455';
        msg.textContent=EDIT_ID
          ? `Draft ${res.no_ba||''} diperbarui. Menunggu review SPV.`
          : `Draft ${res.incident_no} · ${res.no_ba||''} tersimpan dengan ${paths.length} foto evidence. Menunggu review SPV.`;
        localStorage.removeItem(draftKey());
        resetForm();
        setTimeout(async()=>{
          $('incidentModal').classList.remove('show');
          PERIOD=d.date.slice(0,7);
          initPeriods();
          await loadHistory();
          document.querySelector('.panel').scrollIntoView({behavior:'smooth'});
        },750);
      }catch(e){
        msg.style.color='#c42d26';
        msg.textContent='Gagal: '+cleanErr(e?.message||String(e));
      }finally{
        b.disabled=false;
        setBuild();
      }
    };
  }

  setTimeout(setBuild,200);
  setTimeout(setBuild,1000);
  window.__SLS_BREAKAGE_INPUT_EVIDENCE_GUARD='v53';
})();